### ISSUE TITLE
wiki images

### ISSUE THREAD

**Issue by sophiagu** [sophiagu/Learning-JavaScript#3]
![tree diagram](https://cloud.githubusercontent.com/assets/14866379/10505839/770142ac-72df-11e5-8c09-88764a01f8de.png)

**Comment by sophiagu** [comment]
![screen shot 2015-10-20 at 9 15 41 pm](https://cloud.githubusercontent.com/assets/14866379/10625373/7ce80ea4-7770-11e5-896a-4602b26d8136.png)
![screen shot 2015-10-20 at 8 33 23 pm](https://cloud.githubusercontent.com/assets/14866379/10625374/7cedc150-7770-11e5-8548-6ea154d0d4f4.png)
![screen shot 2015-10-20 at 8 34 25 pm](https://cloud.githubusercontent.com/assets/14866379/10625375/7ceeeb48-7770-11e5-9bc6-4e1bb82ec5eb.png)

**Comment by sophiagu** [comment]
![screen shot 2015-10-20 at 9 24 43 pm](https://cloud.githubusercontent.com/assets/14866379/10625424/0db4d692-7771-11e5-9eec-d3520ee919fb.png)

**Comment by sophiagu** [comment]
![screen shot 2015-11-08 at 9 01 34 pm](https://cloud.githubusercontent.com/assets/14866379/11024424/2b48a4a0-865c-11e5-9f86-daded671762f.png)

**Comment by sophiagu** [comment]
![screen shot 2015-11-08 at 10 54 53 pm](https://cloud.githubusercontent.com/assets/14866379/11025752/96eb4a62-866d-11e5-9858-cdd06d7deea4.png)

**Comment by sophia2014** [comment]
![screen shot 2015-12-20 at 3 48 23 am](https://cloud.githubusercontent.com/assets/7086053/11917247/403510ec-a6cd-11e5-96ea-30c1b52df598.png)

**Comment by sophiagu** [comment]
![screen shot 2015-12-20 at 4 03 23 am](https://cloud.githubusercontent.com/assets/14866379/11917277/c00c7ef8-a6ce-11e5-8e9f-f44a0c214f57.png)
![screen shot 2015-12-20 at 4 03 48 am](https://cloud.githubusercontent.com/assets/14866379/11917278/c1ee4efe-a6ce-11e5-85ff-158f3125513b.png)

**Comment by sophiagu** [comment]
![screen shot 2015-12-20 at 4 21 19 am](https://cloud.githubusercontent.com/assets/14866379/11917347/4a5b853e-a6d1-11e5-8477-98ed3b759815.png)

**Comment by sophiagu** [comment]
![screen shot 2015-12-20 at 4 59 41 am](https://cloud.githubusercontent.com/assets/14866379/11917529/d8bbd552-a6d8-11e5-90f3-95c393c0f806.png)
![screen shot 2015-12-20 at 4 51 25 am](https://cloud.githubusercontent.com/assets/14866379/11917530/db493062-a6d8-11e5-98eb-92265d52df0c.png)
![screen shot 2015-12-20 at 5 09 45 am](https://cloud.githubusercontent.com/assets/14866379/11917531/dc8c66a6-a6d8-11e5-8bb5-15e9bcad71aa.png)
